spring:
  datasource:
    url: jdbc:mysql://localhost:3306/covert
    username: ironhacker
    password: 1r0nh4ck3r
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
      include-stacktrace: never
      show-sql: true
  profiles:
    active: load-data

  server:
    error:
      include-message: always
      include-binding-errors: always



