spring:
  datasource:
    url: jdbc:mysql://localhost:3306/covert
    username: ironhacker
    password: 1r0nh4ck3r
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    generate-ddl : true
    hibernate:
      ddl-auto: create-drop
  profiles:
    active: load-data



